// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLAkSQQXnfWcGy117LTrDiKtxDQNaSKCs',
    appId: '1:54006036158:web:a301cf2c0640a9aa6a90ef',
    messagingSenderId: '54006036158',
    projectId: 'dataplate-15972',
    authDomain: 'dataplate-15972.firebaseapp.com',
    storageBucket: 'dataplate-15972.appspot.com',
    measurementId: 'G-JCTXP5FQFQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTDgnFTeuDlHHCAeo9wkxiW3kRCOuD9og',
    appId: '1:54006036158:android:1a4e091fd908e84c6a90ef',
    messagingSenderId: '54006036158',
    projectId: 'dataplate-15972',
    storageBucket: 'dataplate-15972.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1wt5-12TPW56NAYKLxMUx5VMTGm5v8Vw',
    appId: '1:54006036158:ios:81fd63a24db1c0ea6a90ef',
    messagingSenderId: '54006036158',
    projectId: 'dataplate-15972',
    storageBucket: 'dataplate-15972.appspot.com',
    iosClientId: '54006036158-6f171p34f8mhqubfj7equnbe709pf2va.apps.googleusercontent.com',
    iosBundleId: 'com.example.client',
  );
}
